---
- name: Install and Configure MySQL
  hosts: db
  become: yes
  vars:
    mysql_root_password: password
  tasks:
    - name: Update APT cache
      become: yes
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'
      tags:
        - update_cache

    - name: Install MySQL Server
      become: yes
      apt:
        name: mysql-server
        state: present
      when: ansible_os_family == 'Debian'
      tags:
        - install_mysql
    - name: install python
      apt:
       name: python3-pymysql
       state: present

    - name: Start MySQL service
      become: yes
      service:
        name: mysql
        state: started
      tags:
        - start_mysql
