---
- name: install nginx
  hosts: api
  become: true
  tasks:
  - name: install nginx on ubuntu
    apt:
      name: nginx
      state: present
      update_cache: true

  - name: start nginx
    service:
      name: nginx
      enabled: yes
      state: started

  - name: copy html
    copy:
      src: index.html
      dest: /var/www/html/index.html